services:
  plaited:
    container_name: ${CONTAINER_NAME}_${TAG}
    entrypoint: ${ENTRYPOINT}
    stdin_open: true # docker run -i
    tty: true # docker run -t
    build:
      context: .
      args:
        - TAG=${TAG}
    volumes:
      - .:/plaited:delegated
      - /plaited/.yarn
      - /plaited/node_modules
